# Generated by Django 4.1.2 on 2022-10-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Details', models.JSONField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.group')),
            ],
        ),
    ]
