# Generated by Django 4.1.2 on 2022-10-23 12:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('Title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('SimplifyDebt', models.BooleanField(default=False)),
                ('PayMap', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('Balance', models.JSONField(null=True)),
            ],
        ),
    ]
